version: '3.8'

services:
  backend:
    image: javimartinluque/backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - h2data:/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}

volumes:
  h2data: