version: '3.8'

services:
  backend:
    image: javimartinluque/backend:latest  # Nombre de la imagen en Docker Hub
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - h2data:/data

  frontend:
    image: javimartinluque/frontend:latest  # Nombre de la imagen en Docker Hub
    ports:
      - "4200:80"

volumes:
  h2data:


