version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/src
    #command: mvn clean package  # Para que el contenedor use Maven y ejecute el backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app


