version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"  # Backend sigue escuchando en el puerto 8080

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"  # Cambia el puerto a 4200 para el frontend
